--
-- PostgreSQL database dump
--

-- Dumped from database version 10.11
-- Dumped by pg_dump version 12.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


ALTER TABLE public.alembic_version OWNER TO postgres;

--
-- Name: instafluencer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.instafluencer (
    id integer NOT NULL,
    username character varying NOT NULL,
    full_name character varying NOT NULL,
    profile_pic_link character varying NOT NULL,
    profile_link character varying NOT NULL,
    followers integer NOT NULL,
    posts_per_week double precision NOT NULL,
    engagement double precision NOT NULL,
    hashtags character varying[] NOT NULL
);


ALTER TABLE public.instafluencer OWNER TO postgres;

--
-- Name: instafluencer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.instafluencer_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.instafluencer_id_seq OWNER TO postgres;

--
-- Name: instafluencer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.instafluencer_id_seq OWNED BY public.instafluencer.id;


--
-- Name: saved_insta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.saved_insta (
    id integer NOT NULL,
    searcher_username character varying NOT NULL,
    insta_fluencer_id integer NOT NULL,
    date_saved timestamp without time zone
);


ALTER TABLE public.saved_insta OWNER TO postgres;

--
-- Name: saved_insta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.saved_insta_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.saved_insta_id_seq OWNER TO postgres;

--
-- Name: saved_insta_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.saved_insta_id_seq OWNED BY public.saved_insta.id;


--
-- Name: instafluencer id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.instafluencer ALTER COLUMN id SET DEFAULT nextval('public.instafluencer_id_seq'::regclass);


--
-- Name: saved_insta id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_insta ALTER COLUMN id SET DEFAULT nextval('public.saved_insta_id_seq'::regclass);


--
-- Data for Name: alembic_version; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.alembic_version (version_num) FROM stdin;
\.


--
-- Data for Name: instafluencer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.instafluencer (id, username, full_name, profile_pic_link, profile_link, followers, posts_per_week, engagement, hashtags) FROM stdin;
1	hatch_macleay	Hatch@Macleay	https://scontent-atl3-2.cdninstagram.com/v/t51.2885-19/s150x150/28766802_264825497391330_9106834709232484352_n.jpg?_nc_ht=scontent-atl3-2.cdninstagram.com&_nc_ohc=YwZVKhkl070AX8Quf1H&tp=1&oh=8b38813c26215d26c88a1e136f4bf91c&oe=6009D1BE	https://www.instagram.com/hatch_macleay/	320	3.70000000000000018	7.70000000000000018	{"college radio"}
2	ebstide52	DJ Eberle	https://scontent-atl3-2.cdninstagram.com/v/t51.2885-19/s150x150/93823978_2512077709033100_5622275644034383872_n.jpg?_nc_ht=scontent-atl3-2.cdninstagram.com&_nc_ohc=kTFsLUR8lWoAX_Gh5dm&tp=1&oh=3d8654d57d046ab663a8c28ee37b5f2d&oe=6009FCE3	https://www.instagram.com/ebstide52/	316	1.30000000000000004	10.1999999999999993	{"college radio",dj}
3	shawnte_passmore	Shawnte Passmore	https://scontent-atl3-2.cdninstagram.com/v/t51.2885-19/s150x150/12256606_726910014109849_1446897449_a.jpg?_nc_ht=scontent-atl3-2.cdninstagram.com&_nc_ohc=X0zeTo_k4zQAX-KjTqe&tp=1&oh=d944d68d65266f8fe3ea6f9c995ab12e&oe=60093C30	https://www.instagram.com/shawnte_passmore/	333	0.800000000000000044	21.1999999999999993	{"college radio"}
4	icehockeystick	Jashvina Shah	https://scontent-atl3-2.cdninstagram.com/v/t51.2885-19/s150x150/75223543_545411459337652_8799032016789045248_n.jpg?_nc_ht=scontent-atl3-2.cdninstagram.com&_nc_ohc=n919lHhK4ogAX9Td-WG&tp=1&oh=3a13bdeaadd5c1c69734d8808d5a720a&oe=600A7191	https://www.instagram.com/icehockeystick/	345	3.10000000000000009	7.20000000000000018	{"college radio"}
\.


--
-- Data for Name: saved_insta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.saved_insta (id, searcher_username, insta_fluencer_id, date_saved) FROM stdin;
\.


--
-- Name: instafluencer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.instafluencer_id_seq', 4, true);


--
-- Name: saved_insta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.saved_insta_id_seq', 1, false);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: instafluencer instafluencer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.instafluencer
    ADD CONSTRAINT instafluencer_pkey PRIMARY KEY (id);


--
-- Name: instafluencer instafluencer_profile_link_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.instafluencer
    ADD CONSTRAINT instafluencer_profile_link_key UNIQUE (profile_link);


--
-- Name: instafluencer instafluencer_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.instafluencer
    ADD CONSTRAINT instafluencer_username_key UNIQUE (username);


--
-- Name: saved_insta saved_insta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_insta
    ADD CONSTRAINT saved_insta_pkey PRIMARY KEY (id);


--
-- Name: saved_insta saved_insta_insta_fluencer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_insta
    ADD CONSTRAINT saved_insta_insta_fluencer_id_fkey FOREIGN KEY (insta_fluencer_id) REFERENCES public.instafluencer(id);


--
-- PostgreSQL database dump complete
--
