"""modified: SavedInsta username to searcher_username

Revision ID: 757e11dccf3b
Revises: 
Create Date: 2020-11-29 19:54:18.633417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '757e11dccf3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_insta', sa.Column('searcher_username', sa.String(), nullable=False))
    op.alter_column('saved_insta', 'date_saved',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('saved_insta_username_key', 'saved_insta', type_='unique')
    op.create_unique_constraint(None, 'saved_insta', ['searcher_username'])
    op.drop_column('saved_insta', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_insta', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'saved_insta', type_='unique')
    op.create_unique_constraint('saved_insta_username_key', 'saved_insta', ['username'])
    op.alter_column('saved_insta', 'date_saved',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('saved_insta', 'searcher_username')
    # ### end Alembic commands ###
